package xyz.apex.minecraft.fantasyfurniture.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import xyz.apex.minecraft.fantasyfurniture.FantasyFurniture;
import xyz.apex.minecraft.fantasyfurniture.registry.ModBlocks;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {

    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider,
                               ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, FantasyFurniture.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        // minecraft:mineable/axe - all wood furniture blocks
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(ModBlocks.FURNITURE_STATION.get())
                .add(ModBlocks.NORDIC_WALL_LIGHT.get())
                .add(ModBlocks.NORDIC_FLOOR_LIGHT.get())
                .add(ModBlocks.NORDIC_CHANDELIER_LIGHT.get())
                .add(ModBlocks.NORDIC_TABLE.get())
                .add(ModBlocks.NORDIC_TABLE_WIDE.get())
                .add(ModBlocks.NORDIC_TABLE_LARGE.get())
                .add(ModBlocks.NORDIC_CHAIR.get())
                .add(ModBlocks.NORDIC_BENCH.get())
                .add(ModBlocks.NORDIC_STOOL.get())
                .add(ModBlocks.NORDIC_CUSHION.get())
                .add(ModBlocks.NORDIC_SHELF.get())
                .add(ModBlocks.NORDIC_SOFA.get())
                .add(ModBlocks.NORDIC_DRAWER.get())
                .add(ModBlocks.NORDIC_LOCKBOX.get())
                .add(ModBlocks.NORDIC_DESK_LEFT.get())
                .add(ModBlocks.NORDIC_DESK_RIGHT.get())
                .add(ModBlocks.NORDIC_DRESSER.get())
                .add(ModBlocks.NORDIC_COUNTER.get())
                .add(ModBlocks.NORDIC_CHEST.get())
                .add(ModBlocks.NORDIC_WARDROBE_BOTTOM.get())
                .add(ModBlocks.NORDIC_WARDROBE_TOP.get())
                .add(ModBlocks.NORDIC_BOOKSHELF.get())
                .add(ModBlocks.NORDIC_BED_SINGLE.get())
                .add(ModBlocks.NORDIC_BED_DOUBLE.get())
                .add(ModBlocks.NORDIC_DOOR_SINGLE.get())
                .add(ModBlocks.NORDIC_DOOR_DOUBLE.get())
                .add(ModBlocks.NORDIC_PAINTING_SMALL.get())
                .add(ModBlocks.NORDIC_PAINTING_WIDE.get())
                .add(ModBlocks.NORDIC_BOILED_CREME_TREATS.get())
                .add(ModBlocks.NORDIC_SWEETROLLS.get())
                .add(ModBlocks.NORDIC_MEAD_BOTTLES.get())
                .add(ModBlocks.NORDIC_SOUL_GEMS_LIGHT.get())
                .add(ModBlocks.NORDIC_SOUL_GEMS_DARK.get())
                .add(ModBlocks.ROYAL_WALL_LIGHT.get())
                .add(ModBlocks.ROYAL_FLOOR_LIGHT.get())
                .add(ModBlocks.ROYAL_CHANDELIER_LIGHT.get())
                .add(ModBlocks.ROYAL_TABLE.get())
                .add(ModBlocks.ROYAL_CHAIR.get())
                .add(ModBlocks.ROYAL_BENCH.get())
                .add(ModBlocks.ROYAL_STOOL.get())
                .add(ModBlocks.ROYAL_CUSHION.get())
                .add(ModBlocks.ROYAL_SHELF.get())
                .add(ModBlocks.ROYAL_SOFA.get())
                .add(ModBlocks.ROYAL_DRAWER.get())
                .add(ModBlocks.ROYAL_LOCKBOX.get())
                .add(ModBlocks.ROYAL_DESK_LEFT.get())
                .add(ModBlocks.ROYAL_DESK_RIGHT.get())
                .add(ModBlocks.ROYAL_DRESSER.get())
                .add(ModBlocks.ROYAL_COUNTER.get())
                .add(ModBlocks.ROYAL_CHEST.get())
                .add(ModBlocks.ROYAL_WARDROBE_BOTTOM.get())
                .add(ModBlocks.ROYAL_WARDROBE_TOP.get())
                .add(ModBlocks.ROYAL_BOOKSHELF.get())
                .add(ModBlocks.ROYAL_BED_SINGLE.get())
                .add(ModBlocks.ROYAL_BED_DOUBLE.get())
                .add(ModBlocks.ROYAL_DOOR_SINGLE.get())
                .add(ModBlocks.ROYAL_DOOR_DOUBLE.get())
                .add(ModBlocks.ROYAL_PAINTING_SMALL.get())
                .add(ModBlocks.ROYAL_PAINTING_WIDE.get())
                .add(ModBlocks.ROYAL_CROWN.get())
                .add(ModBlocks.ROYAL_CUSHIONED_CROWN.get())
                .add(ModBlocks.ROYAL_CANDELABRA.get())
                .add(ModBlocks.ROYAL_CHALICES.get())
                .add(ModBlocks.ROYAL_PLATTER.get())
                .add(ModBlocks.ROYAL_FOOD.get())
                .add(ModBlocks.ROYAL_FLOOR_CUSHION.get())
                .add(ModBlocks.ROYAL_WALL_MIRROR.get())
                .add(ModBlocks.ROYAL_WALL_MIRROR_TALL.get())
                .add(ModBlocks.DUNMER_WALL_LIGHT.get())
                .add(ModBlocks.DUNMER_FLOOR_LIGHT.get())
                .add(ModBlocks.DUNMER_CHANDELIER_LIGHT.get())
                .add(ModBlocks.DUNMER_TABLE_SMALL.get())
                .add(ModBlocks.DUNMER_TABLE_WIDE.get())
                .add(ModBlocks.DUNMER_TABLE_LARGE.get())
                .add(ModBlocks.DUNMER_CHAIR.get())
                .add(ModBlocks.DUNMER_BENCH.get())
                .add(ModBlocks.DUNMER_STOOL.get())
                .add(ModBlocks.DUNMER_CUSHION.get())
                .add(ModBlocks.DUNMER_SHELF.get())
                .add(ModBlocks.DUNMER_SOFA.get())
                .add(ModBlocks.DUNMER_DRAWER.get())
                .add(ModBlocks.DUNMER_LOCKBOX.get())
                .add(ModBlocks.DUNMER_DESK_LEFT.get())
                .add(ModBlocks.DUNMER_DESK_RIGHT.get())
                .add(ModBlocks.DUNMER_DRESSER.get())
                .add(ModBlocks.DUNMER_COUNTER.get())
                .add(ModBlocks.DUNMER_CHEST.get())
                .add(ModBlocks.DUNMER_WARDROBE_BOTTOM.get())
                .add(ModBlocks.DUNMER_WARDROBE_TOP.get())
                .add(ModBlocks.DUNMER_BOOKSHELF.get())
                .add(ModBlocks.DUNMER_BED_SINGLE.get())
                .add(ModBlocks.DUNMER_BED_DOUBLE.get())
                .add(ModBlocks.DUNMER_DOOR_SINGLE.get())
                .add(ModBlocks.DUNMER_DOOR_DOUBLE.get())
                .add(ModBlocks.DUNMER_PAINTING_SMALL.get())
                .add(ModBlocks.DUNMER_PAINTING_WIDE.get())
                .add(ModBlocks.DUNMER_POTTERY_0.get())
                .add(ModBlocks.DUNMER_POTTERY_1.get())
                .add(ModBlocks.VENTHYR_WALL_LIGHT.get())
                .add(ModBlocks.VENTHYR_FLOOR_LIGHT.get())
                .add(ModBlocks.VENTHYR_CHANDELIER_LIGHT.get())
                .add(ModBlocks.VENTHYR_TABLE_SMALL.get())
                .add(ModBlocks.VENTHYR_TABLE_SMALL_FANCY.get())
                .add(ModBlocks.VENTHYR_TABLE_WIDE.get())
                .add(ModBlocks.VENTHYR_TABLE_WIDE_FANCY.get())
                .add(ModBlocks.VENTHYR_TABLE_LARGE.get())
                .add(ModBlocks.VENTHYR_TABLE_LARGE_FANCY.get())
                .add(ModBlocks.VENTHYR_CHAIR.get())
                .add(ModBlocks.VENTHYR_BENCH.get())
                .add(ModBlocks.VENTHYR_STOOL.get())
                .add(ModBlocks.VENTHYR_CUSHION.get())
                .add(ModBlocks.VENTHYR_SHELF.get())
                .add(ModBlocks.VENTHYR_SOFA.get())
                .add(ModBlocks.VENTHYR_DRAWER.get())
                .add(ModBlocks.VENTHYR_LOCKBOX.get())
                .add(ModBlocks.VENTHYR_DESK_LEFT.get())
                .add(ModBlocks.VENTHYR_DESK_RIGHT.get())
                .add(ModBlocks.VENTHYR_DRESSER.get())
                .add(ModBlocks.VENTHYR_COUNTER.get())
                .add(ModBlocks.VENTHYR_CHEST.get())
                .add(ModBlocks.VENTHYR_WARDROBE_BOTTOM.get())
                .add(ModBlocks.VENTHYR_WARDROBE_TOP.get())
                .add(ModBlocks.VENTHYR_BOOKSHELF.get())
                .add(ModBlocks.VENTHYR_BED_SINGLE.get())
                .add(ModBlocks.VENTHYR_BED_DOUBLE.get())
                .add(ModBlocks.VENTHYR_DOOR_SINGLE.get())
                .add(ModBlocks.VENTHYR_DOOR_DOUBLE.get())
                .add(ModBlocks.VENTHYR_PAINTING_SMALL.get())
                .add(ModBlocks.VENTHYR_PAINTING_WIDE.get())
                .add(ModBlocks.VENTHYR_FOOD_0.get())
                .add(ModBlocks.VENTHYR_FOOD_1.get())
                .add(ModBlocks.VENTHYR_TOMES.get())
                .add(ModBlocks.VENTHYR_TEA_CUPS.get())
                .add(ModBlocks.VENTHYR_PLATTER.get())
                .add(ModBlocks.VENTHYR_TEA_SET.get())
                .add(ModBlocks.VENTHYR_BANNER.get())
                .add(ModBlocks.VENTHYR_CANDLES.get())
                .add(ModBlocks.VENTHYR_CHALICES.get())
                .add(ModBlocks.VENTHYR_WIDOW_BLOOM.get())
                .add(ModBlocks.NECROLORD_WALL_LIGHT.get())
                .add(ModBlocks.NECROLORD_FLOOR_LIGHT.get())
                .add(ModBlocks.NECROLORD_CHANDELIER_LIGHT.get())
                .add(ModBlocks.NECROLORD_TABLE_SMALL.get())
                .add(ModBlocks.NECROLORD_TABLE_WIDE.get())
                .add(ModBlocks.NECROLORD_TABLE_LARGE.get())
                .add(ModBlocks.NECROLORD_CHAIR.get())
                .add(ModBlocks.NECROLORD_BENCH.get())
                .add(ModBlocks.NECROLORD_STOOL.get())
                .add(ModBlocks.NECROLORD_CUSHION.get())
                .add(ModBlocks.NECROLORD_SHELF.get())
                .add(ModBlocks.NECROLORD_SOFA.get())
                .add(ModBlocks.NECROLORD_DRAWER.get())
                .add(ModBlocks.NECROLORD_LOCKBOX.get())
                .add(ModBlocks.NECROLORD_DESK_LEFT.get())
                .add(ModBlocks.NECROLORD_DESK_RIGHT.get())
                .add(ModBlocks.NECROLORD_DRESSER.get())
                .add(ModBlocks.NECROLORD_COUNTER.get())
                .add(ModBlocks.NECROLORD_CHEST.get())
                .add(ModBlocks.NECROLORD_WARDROBE_BOTTOM.get())
                .add(ModBlocks.NECROLORD_WARDROBE_TOP.get())
                .add(ModBlocks.NECROLORD_BOOKSHELF.get())
                .add(ModBlocks.NECROLORD_BED_SINGLE.get())
                .add(ModBlocks.NECROLORD_BED_DOUBLE.get())
                .add(ModBlocks.NECROLORD_DOOR_SINGLE.get())
                .add(ModBlocks.NECROLORD_DOOR_DOUBLE.get())
                .add(ModBlocks.NECROLORD_PAINTING_SMALL.get())
                .add(ModBlocks.NECROLORD_PAINTING_WIDE.get())
                .add(ModBlocks.NECROLORD_CANDELABRA.get());

        // minecraft:mineable/pickaxe - stone blocks + entire Bone-Skeleton set
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(ModBlocks.NORDIC_OVEN.get())
                .add(ModBlocks.ROYAL_OVEN.get())
                .add(ModBlocks.DUNMER_OVEN.get())
                .add(ModBlocks.VENTHYR_OVEN.get())
                .add(ModBlocks.NECROLORD_OVEN.get())
                // Bone-Skeleton set is pickaxe-mineable (legacy .transform(BlockTransformers::mineablePickaxe))
                .add(ModBlocks.BONE_SKELETON_WALL_LIGHT.get())
                .add(ModBlocks.BONE_SKELETON_FLOOR_LIGHT.get())
                .add(ModBlocks.BONE_SKELETON_CHANDELIER_LIGHT.get())
                .add(ModBlocks.BONE_SKELETON_TABLE_SMALL.get())
                .add(ModBlocks.BONE_SKELETON_TABLE_WIDE.get())
                .add(ModBlocks.BONE_SKELETON_TABLE_LARGE.get())
                .add(ModBlocks.BONE_SKELETON_CHAIR.get())
                .add(ModBlocks.BONE_SKELETON_BENCH.get())
                .add(ModBlocks.BONE_SKELETON_STOOL.get())
                .add(ModBlocks.BONE_SKELETON_SKULL.get())
                .add(ModBlocks.BONE_SKELETON_SHELF.get())
                .add(ModBlocks.BONE_SKELETON_SOFA.get())
                .add(ModBlocks.BONE_SKELETON_DRAWER.get())
                .add(ModBlocks.BONE_SKELETON_LOCKBOX.get())
                .add(ModBlocks.BONE_SKELETON_DESK_LEFT.get())
                .add(ModBlocks.BONE_SKELETON_DESK_RIGHT.get())
                .add(ModBlocks.BONE_SKELETON_DRESSER.get())
                .add(ModBlocks.BONE_SKELETON_COUNTER.get())
                .add(ModBlocks.BONE_SKELETON_CHEST.get())
                .add(ModBlocks.BONE_SKELETON_WARDROBE_BOTTOM.get())
                .add(ModBlocks.BONE_SKELETON_WARDROBE_TOP.get())
                .add(ModBlocks.BONE_SKELETON_BOOKSHELF.get())
                .add(ModBlocks.BONE_SKELETON_BED_SINGLE.get())
                .add(ModBlocks.BONE_SKELETON_BED_DOUBLE.get())
                .add(ModBlocks.BONE_SKELETON_DOOR_SINGLE.get())
                .add(ModBlocks.BONE_SKELETON_DOOR_DOUBLE.get())
                .add(ModBlocks.BONE_SKELETON_PAINTING_SMALL.get())
                .add(ModBlocks.BONE_SKELETON_PAINTING_WIDE.get())
                .add(ModBlocks.BONE_SKELETON_OVEN.get())
                .add(ModBlocks.BONE_SKELETON_CHALICES.get())
                .add(ModBlocks.BONE_SKELETON_PILE.get())
                .add(ModBlocks.BONE_SKELETON_SKULL_BLOSSOMS.get())
                // Bone-Wither set is pickaxe-mineable (legacy .transform(BlockTransformers::mineablePickaxe))
                .add(ModBlocks.BONE_WITHER_WALL_LIGHT.get())
                .add(ModBlocks.BONE_WITHER_FLOOR_LIGHT.get())
                .add(ModBlocks.BONE_WITHER_CHANDELIER_LIGHT.get())
                .add(ModBlocks.BONE_WITHER_TABLE_SMALL.get())
                .add(ModBlocks.BONE_WITHER_TABLE_WIDE.get())
                .add(ModBlocks.BONE_WITHER_TABLE_LARGE.get())
                .add(ModBlocks.BONE_WITHER_CHAIR.get())
                .add(ModBlocks.BONE_WITHER_BENCH.get())
                .add(ModBlocks.BONE_WITHER_STOOL.get())
                .add(ModBlocks.BONE_WITHER_SKULL.get())
                .add(ModBlocks.BONE_WITHER_SHELF.get())
                .add(ModBlocks.BONE_WITHER_SOFA.get())
                .add(ModBlocks.BONE_WITHER_DRAWER.get())
                .add(ModBlocks.BONE_WITHER_LOCKBOX.get())
                .add(ModBlocks.BONE_WITHER_DESK_LEFT.get())
                .add(ModBlocks.BONE_WITHER_DESK_RIGHT.get())
                .add(ModBlocks.BONE_WITHER_DRESSER.get())
                .add(ModBlocks.BONE_WITHER_COUNTER.get())
                .add(ModBlocks.BONE_WITHER_CHEST.get())
                .add(ModBlocks.BONE_WITHER_WARDROBE_BOTTOM.get())
                .add(ModBlocks.BONE_WITHER_WARDROBE_TOP.get())
                .add(ModBlocks.BONE_WITHER_BOOKSHELF.get())
                .add(ModBlocks.BONE_WITHER_BED_SINGLE.get())
                .add(ModBlocks.BONE_WITHER_BED_DOUBLE.get())
                .add(ModBlocks.BONE_WITHER_DOOR_SINGLE.get())
                .add(ModBlocks.BONE_WITHER_DOOR_DOUBLE.get())
                .add(ModBlocks.BONE_WITHER_PAINTING_SMALL.get())
                .add(ModBlocks.BONE_WITHER_PAINTING_WIDE.get())
                .add(ModBlocks.BONE_WITHER_OVEN.get())
                .add(ModBlocks.BONE_WITHER_CHALICES.get())
                .add(ModBlocks.BONE_WITHER_PILE.get())
                .add(ModBlocks.BONE_WITHER_SKULL_BLOSSOMS.get());

        // minecraft:wool
        tag(BlockTags.WOOL)
                .add(ModBlocks.NORDIC_WOOL.get())
                .add(ModBlocks.ROYAL_WOOL.get())
                .add(ModBlocks.DUNMER_WOOL.get())
                .add(ModBlocks.VENTHYR_WOOL.get())
                .add(ModBlocks.NECROLORD_WOOL.get())
                .add(ModBlocks.BONE_SKELETON_WOOL.get())
                .add(ModBlocks.BONE_WITHER_WOOL.get());

        // minecraft:wool_carpets
        tag(BlockTags.WOOL_CARPETS)
                .add(ModBlocks.NORDIC_CARPET.get())
                .add(ModBlocks.ROYAL_CARPET.get())
                .add(ModBlocks.DUNMER_CARPET.get())
                .add(ModBlocks.VENTHYR_CARPET.get())
                .add(ModBlocks.NECROLORD_CARPET.get())
                .add(ModBlocks.BONE_SKELETON_CARPET.get())
                .add(ModBlocks.BONE_WITHER_CARPET.get());

        // minecraft:beds
        tag(BlockTags.BEDS)
                .add(ModBlocks.NORDIC_BED_SINGLE.get())
                .add(ModBlocks.NORDIC_BED_DOUBLE.get())
                .add(ModBlocks.ROYAL_BED_SINGLE.get())
                .add(ModBlocks.ROYAL_BED_DOUBLE.get())
                .add(ModBlocks.DUNMER_BED_SINGLE.get())
                .add(ModBlocks.DUNMER_BED_DOUBLE.get())
                .add(ModBlocks.VENTHYR_BED_SINGLE.get())
                .add(ModBlocks.VENTHYR_BED_DOUBLE.get())
                .add(ModBlocks.NECROLORD_BED_SINGLE.get())
                .add(ModBlocks.NECROLORD_BED_DOUBLE.get())
                .add(ModBlocks.BONE_SKELETON_BED_SINGLE.get())
                .add(ModBlocks.BONE_SKELETON_BED_DOUBLE.get())
                .add(ModBlocks.BONE_WITHER_BED_SINGLE.get())
                .add(ModBlocks.BONE_WITHER_BED_DOUBLE.get());

        // minecraft:doors
        tag(BlockTags.DOORS)
                .add(ModBlocks.NORDIC_DOOR_SINGLE.get())
                .add(ModBlocks.NORDIC_DOOR_DOUBLE.get())
                .add(ModBlocks.ROYAL_DOOR_SINGLE.get())
                .add(ModBlocks.ROYAL_DOOR_DOUBLE.get())
                .add(ModBlocks.DUNMER_DOOR_SINGLE.get())
                .add(ModBlocks.DUNMER_DOOR_DOUBLE.get())
                .add(ModBlocks.VENTHYR_DOOR_SINGLE.get())
                .add(ModBlocks.VENTHYR_DOOR_DOUBLE.get())
                .add(ModBlocks.NECROLORD_DOOR_SINGLE.get())
                .add(ModBlocks.NECROLORD_DOOR_DOUBLE.get())
                .add(ModBlocks.BONE_SKELETON_DOOR_SINGLE.get())
                .add(ModBlocks.BONE_SKELETON_DOOR_DOUBLE.get())
                .add(ModBlocks.BONE_WITHER_DOOR_SINGLE.get())
                .add(ModBlocks.BONE_WITHER_DOOR_DOUBLE.get());
    }
}
